image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      export Phase_DIR="C:\Program Files\I3DR\Phase"
      dotnet restore
      dotnet build

vscode:
  extensions:
    - muhammad-sammy.csharp
