image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      export Phase_DIR="/opt/i3dr/phase"
      dotnet restore
      dotnet build

vscode:
  extensions:
    - muhammad-sammy.csharp
