var hierarchy =
[
    [ "I3DR.Phase.StereoCamera.AbstractStereoCamera", "class_i3_d_r_1_1_phase_1_1_stereo_camera_1_1_abstract_stereo_camera.html", [
      [ "I3DR.Phase.StereoCamera.DeimosStereoCamera", "class_i3_d_r_1_1_phase_1_1_stereo_camera_1_1_deimos_stereo_camera.html", null ],
      [ "I3DR.Phase.StereoCamera.PhobosStereoCamera", "class_i3_d_r_1_1_phase_1_1_stereo_camera_1_1_phobos_stereo_camera.html", null ],
      [ "I3DR.Phase.StereoCamera.PylonStereoCamera", "class_i3_d_r_1_1_phase_1_1_stereo_camera_1_1_pylon_stereo_camera.html", null ],
      [ "I3DR.Phase.StereoCamera.TitaniaStereoCamera", "class_i3_d_r_1_1_phase_1_1_stereo_camera_1_1_titania_stereo_camera.html", null ],
      [ "I3DR.Phase.StereoCamera.UVCStereoCamera", "class_i3_d_r_1_1_phase_1_1_stereo_camera_1_1_u_v_c_stereo_camera.html", null ]
    ] ],
    [ "I3DR.Phase.StereoMatcher.AbstractStereoMatcher", "class_i3_d_r_1_1_phase_1_1_stereo_matcher_1_1_abstract_stereo_matcher.html", [
      [ "I3DR.Phase.StereoMatcher.StereoBM", "class_i3_d_r_1_1_phase_1_1_stereo_matcher_1_1_stereo_b_m.html", null ],
      [ "I3DR.Phase.StereoMatcher.StereoI3DRSGM", "class_i3_d_r_1_1_phase_1_1_stereo_matcher_1_1_stereo_i3_d_r_s_g_m.html", null ],
      [ "I3DR.Phase.StereoMatcher.StereoSGBM", "class_i3_d_r_1_1_phase_1_1_stereo_matcher_1_1_stereo_s_g_b_m.html", null ]
    ] ],
    [ "I3DR.CPhase.StereoCamera.CAbstractStereoCamera", "class_i3_d_r_1_1_c_phase_1_1_stereo_camera_1_1_c_abstract_stereo_camera.html", null ],
    [ "I3DR.CPhase.StereoMatcher.CAbstractStereoMatcher", "class_i3_d_r_1_1_c_phase_1_1_stereo_matcher_1_1_c_abstract_stereo_matcher.html", null ],
    [ "I3DR.Phase.Calib.CameraCalibration", "class_i3_d_r_1_1_phase_1_1_calib_1_1_camera_calibration.html", null ],
    [ "I3DR.Phase.StereoCamera.CameraDeviceInfo", "struct_i3_d_r_1_1_phase_1_1_stereo_camera_1_1_camera_device_info.html", null ],
    [ "I3DR.Phase.StereoCamera.CameraReadResult", "struct_i3_d_r_1_1_phase_1_1_stereo_camera_1_1_camera_read_result.html", null ],
    [ "I3DR.CPhase.Calib.CCameraCalibration", "class_i3_d_r_1_1_c_phase_1_1_calib_1_1_c_camera_calibration.html", null ],
    [ "I3DR.CPhase.StereoCamera.CDeimosStereoCamera", "class_i3_d_r_1_1_c_phase_1_1_stereo_camera_1_1_c_deimos_stereo_camera.html", null ],
    [ "I3DR.CPhase.Types.CMatrixFloat", "class_i3_d_r_1_1_c_phase_1_1_types_1_1_c_matrix_float.html", null ],
    [ "I3DR.CPhase.Types.CMatrixUInt8", "class_i3_d_r_1_1_c_phase_1_1_types_1_1_c_matrix_u_int8.html", null ],
    [ "I3DR.CPhase.StereoCamera.CPhobosStereoCamera", "class_i3_d_r_1_1_c_phase_1_1_stereo_camera_1_1_c_phobos_stereo_camera.html", null ],
    [ "I3DR.CPhase.StereoCamera.CPylonStereoCamera", "class_i3_d_r_1_1_c_phase_1_1_stereo_camera_1_1_c_pylon_stereo_camera.html", null ],
    [ "I3DR.CPhase.StereoMatcher.CStereoBM", "class_i3_d_r_1_1_c_phase_1_1_stereo_matcher_1_1_c_stereo_b_m.html", null ],
    [ "I3DR.CPhase.StereoCamera.CStereoCamera", "class_i3_d_r_1_1_c_phase_1_1_stereo_camera_1_1_c_stereo_camera.html", null ],
    [ "I3DR.CPhase.Calib.CStereoCameraCalibration", "class_i3_d_r_1_1_c_phase_1_1_calib_1_1_c_stereo_camera_calibration.html", null ],
    [ "I3DR.CPhase.StereoMatcher.CStereoI3DRSGM", "class_i3_d_r_1_1_c_phase_1_1_stereo_matcher_1_1_c_stereo_i3_d_r_s_g_m.html", null ],
    [ "I3DR.CPhase.StereoMatcher.CStereoMatcher", "class_i3_d_r_1_1_c_phase_1_1_stereo_matcher_1_1_c_stereo_matcher.html", null ],
    [ "I3DR.CPhase.StereoMatcher.CStereoSGBM", "class_i3_d_r_1_1_c_phase_1_1_stereo_matcher_1_1_c_stereo_s_g_b_m.html", null ],
    [ "I3DR.CPhase.StereoCamera.CTitaniaStereoCamera", "class_i3_d_r_1_1_c_phase_1_1_stereo_camera_1_1_c_titania_stereo_camera.html", null ],
    [ "I3DR.CPhase.CUtils", "class_i3_d_r_1_1_c_phase_1_1_c_utils.html", null ],
    [ "I3DR.CPhase.StereoCamera.CUVCStereoCamera", "class_i3_d_r_1_1_c_phase_1_1_stereo_camera_1_1_c_u_v_c_stereo_camera.html", null ],
    [ "I3DR.CPhase.CVersion", "class_i3_d_r_1_1_c_phase_1_1_c_version.html", null ],
    [ "I3DR.PhaseDemo.DemoCameraRead", "class_i3_d_r_1_1_phase_demo_1_1_demo_camera_read.html", null ],
    [ "I3DR.PhaseDemo.DemoCameraReadThread", "class_i3_d_r_1_1_phase_demo_1_1_demo_camera_read_thread.html", null ],
    [ "I3DR.Phase.Types.MatrixFloat", "class_i3_d_r_1_1_phase_1_1_types_1_1_matrix_float.html", null ],
    [ "I3DR.Phase.Types.MatrixUInt8", "class_i3_d_r_1_1_phase_1_1_types_1_1_matrix_u_int8.html", null ],
    [ "I3DR.Phase.StereoCamera.StereoCamera", "class_i3_d_r_1_1_phase_1_1_stereo_camera_1_1_stereo_camera.html", null ],
    [ "I3DR.Phase.Calib.StereoCameraCalibration", "class_i3_d_r_1_1_phase_1_1_calib_1_1_stereo_camera_calibration.html", null ],
    [ "I3DR.Phase.Types.StereoImagePair", "struct_i3_d_r_1_1_phase_1_1_types_1_1_stereo_image_pair.html", null ],
    [ "I3DR.Phase.StereoMatcher.StereoMatcher", "class_i3_d_r_1_1_phase_1_1_stereo_matcher_1_1_stereo_matcher.html", null ],
    [ "I3DR.Phase.StereoMatcher.StereoMatcherComputeResult", "struct_i3_d_r_1_1_phase_1_1_stereo_matcher_1_1_stereo_matcher_compute_result.html", null ],
    [ "I3DR.Phase.StereoMatcher.StereoParams", "struct_i3_d_r_1_1_phase_1_1_stereo_matcher_1_1_stereo_params.html", null ],
    [ "I3DR.Phase.Utils", "class_i3_d_r_1_1_phase_1_1_utils.html", null ],
    [ "I3DR.Phase.Version", "class_i3_d_r_1_1_phase_1_1_version.html", null ]
];