name: Build

on:
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

env:
  PHASE_VERSION: v0.2.0
  PHASE_REPO: i3drobotics/phase

jobs:
  # Build / test
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.408'
      # Install Phase
      - name: Download Phase
        uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ env.PHASE_REPO }}
          tag: ${{ env.PHASE_VERSION }}
          fileName: phase-${{ env.PHASE_VERSION }}-windows-x86_64.zip
      - name: Install Phase
        shell: powershell
        run: |
          Expand-Archive -Path phase-${{ env.PHASE_VERSION }}-windows-x86_64.zip -DestinationPath "C:\Program Files\I3DR\Phase"
          Get-ChildItem -Path "C:\Program Files\I3DR\Phase"
          echo "C:\Program Files\I3DR\Phase\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      # Build
      - name: Build
        shell: bash
        run: |
          dotnet build --configuration Release
        env:
          Phase_DIR: "C:\\Program Files\\I3DR\\Phase"
      # Unit Test
      - name: Unit Test
        shell: bash
        run: |
          dotnet test test/unit/phasecsharp-unit-test.csproj
          dotnet test test/perf/phasecsharp-perf-test.csproj
        env:
          Phase_DIR: "C:\\Program Files\\I3DR\\Phase"
