name: Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

env:
  PHASE_VERSION: v0.1.2-2
  PHASE_REPO: i3drobotics/phase

jobs:
  # Build / test
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.408'
      # Install Phase
      - name: Download Phase
        uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ env.PHASE_REPO }}
          tag: ${{ env.PHASE_VERSION }}
          fileName: phase-${{ env.PHASE_VERSION }}-windows-x86_64.zip
      - name: Install Phase
        shell: powershell
        run: |
          Expand-Archive -Path phase-${{ env.PHASE_VERSION }}-windows-x86_64.zip -DestinationPath "C:\Temp\Phase"
          New-Item "C:\Program Files\I3DR\Phase" -type directory
          Move-Item -Path "C:\Temp\Phase\install\*" -Destination "C:\Program Files\I3DR\Phase" -force
          Get-ChildItem -Path "C:\Program Files\I3DR\Phase"
          echo "C:\Program Files\I3DR\Phase\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      # Build
      - name: Build
        shell: bash
        run: |
          dotnet build --configuration Release
      # Unit Test
      - name: Unit Test
        shell: bash
        run: |
          dotnet test
